### ISSUE TITLE
Использовать для конфигурации yaml файлы

### ISSUE THREAD

**Issue by pavelpower** [hhru/kanban-meter#24]
Перенастройка в python файлах - имеет некоторые недостатки для использования в масштабной компании.
Особенно там где процессы в разных командах контекстно отличаются.

По этому хорошо бы дать возможность настраивать при помощи yaml

project-name.yml
```yaml
team_name: HH
statuses_backlog:
    - New
    - Backlog
statuses_todo:
    - ToDo
    - "Ready to develop"
statuses_inprogres:
   - Developing
   - Testing
   - InProgress
   - Analysis
statuses_buffer:
  - "Ready to Testing"
  - "Ready to Review"
....

```
